# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-08-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200815_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleinfo',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
