# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-08-17 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_peopleinfo_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleinfo',
            name='is_show',
        ),
    ]
